name: 5. Repo Sync

on:
  schedule:
    - cron:  "0 3 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Main Branch
        uses: tgymnich/fork-sync@v2
        with:
          base: main
          head: main
          pr_title: "Merge"
          merge_method: "merge"
          token: ${{ secrets.GH_PAT }}

      - name: Sync Dev Branch
        uses: tgymnich/fork-sync@v2
        with:
          base: dev
          head: dev
          pr_title: "Merge"
          merge_method: "merge"
          token: ${{ secrets.GH_PAT }}
